### ISSUE TITLE
Make BBEdit aware of underlying changes

### ISSUE THREAD

**Issue by ballo** [cngarrison/rbbedit#3]
If I open a file locally, BBEdit is aware if another process like git has updated (over-written) the file I'm working on. This is the one feature I'm missing so I can use BBEdit to edit remote files instead of vi

**Comment by cngarrison** [comment]
You need to use one of the methods that presents the remote server as a local filesystem, that way BBEdit can watch files for changes. I suggest using ExpanDrive since `rbbedit` already has support for that. If you have another solution for mounting remote filesystems, let me know and I'll look at adding support for it.

**Comment by ballo** [comment]
Surely there is a way for rbbedit to keep track of the file like joe does, no?

**Comment by ballo** [comment]
BTW, mounting a remote volume via ntp wasn't practical.

**Comment by cngarrison** [comment]
It would be a non-trivial task to add monitoring files for changes, and even if the script could do that I'm not aware of any way to tell BBEdit the re-read the file. `rbbedit` doesn't do anything more than `bbedit` does. Both of those tools are methods of telling BBEdit to open and edit files. Neither of those tools do any file editing themselves. 

In any case, if you can see how it could be done; feel free to create a PR with the changes to support it. 

BTW, I don't know what (or who) "joe" is, so I can't make comparisons. Maybe just get 'joe' to do what you want.

I'm not sure what ntp is in relation to mounting remote volumes; do you mean ftp? If so, that won't do what you want either, BBEdit opens the remote file, but doesn't keep re-reading the remote file to look for changes. You can use the File menu to request the file be re-read from disk, so maybe scripting that will do what you want. 

Since `rbbedit` already does what you're asking with the 'expan' `copy-method`, I'm closing this issue. I added support for ExpanDrive for exactly the reason you are requesting. That is the solution to do what you are wanting. 

So, your options are to use ExpanDrive, find another similar tool which I'm willing to support (there are __heaps__ of FUSE options), or add the file monitoring support yourself and create a PR with the changes.

**Comment by ballo** [comment]
I really don't see how ExpanDrive is a solution to anything. It looks like a cloud drive which has nothing to do with this, and it only supports Mac and Windows. I really don't see the point.

joe is just a text editor. 

When I said ntp I meant to say NFS.

I don't see the option to re-read from disk. "Revert" doesn't behave that way when opening files via sftp. You're not even allowed to use that command when BBEdit thinks the file is current (i.e. after a save). 

Maybe you mean something other than http://www.expandrive.com/?

**Comment by cngarrison** [comment]
I could possibly add support for NFS mounts; there would need to be some way of telling `bbedit` what the local mount point is. 

I was thinking of the 'Reload from Disk' command, which doesn't seem to be available for files opened via (s)ftp, so there's not much that `rbbedit` can do to solve that. 

Yes, that is the link for ExpanDrive. Have you tried it yet? Once you've tried it; if doesn't work for you then please explain why (preferably via a new issue) and I'll look into why it's not working for you. 

If you provide a link for the documentation for joe which shows how the opening and editing of remote files work, I can have a look at it. Quick review of the man page didn't reveal any options for opening remote files. My guess is that joe implements it's own file transfer protocol that allows it to do what you want. IOW, it's built into the editor.

**Comment by ballo** [comment]
Well, like I said, NFS was impractical. I only tried it because it would possibly keep track of what files were open transparently, but it requires a low latency connection.

A solution to the problem cannot use sftp. 

ExpanDrive is Windows and Mac only and doesn't appear to have source available. Good enough reason? It's also cloud based and shady as fuck. If it needs the cloud that's a no-go. Cloud is for family photos (assuming you don't care who hacks it), not source under NDA. 

joe is just an example of a local program which knows when other programs on the same system modify the underlying file. To see how this works have joe open a new file like 'joe /tmp/tempfile' then open the same file with vi using another terminal window 'vi /tmp/tempfile' write some stuff and save. joe knows the file was modified and says "Notice: File on disk changed! (hit ^C to continue)".

**Comment by cngarrison** [comment]
I didn't know ExpanDrive now supported Windows as well, good for them. BBEdit is Mac-only, so what is your gripe about using a Mac program. If you don't want to use closed source, then find a different FUSE solution. I'm pretty sure ExpanDrive is based on FUSE anyway. They are saying it's cloud-based as part of their marketing I guess. I use it for connecting to my own servers; ignore the 'cloud' label. Or find another FUSE solution. 

I've said a few times now that BBEdit doesn't support what you want, and `rbbedit` is just a way to pass files to BBEdit to open. It's not doesn't track state or anything else. And I've given you multiple solutions to your problem; I'm not a magician to magically make solutions upon demand. 

Actually try ExpanDrive, or try one of the FUSE solutions, and then get back to me. Or show me another way to monitor file status on a remote filesystem. I have no desire to write a custom protocol to do that; it would be a huge amount of effort for little gain since other solutions already exist.

If joe is an example of a local program that can watch file state, why even bother mentioning it. BBEdit already does that as well. You are comparing apples to baseballs. If it has a way to monitor file state on a remote system, then that is interesting and I'll look into it.

What you are asking is for BBEdit to be able to monitor file state on a remote system. That means you need to present that remote system as a local filesystem. Period. ExpanDrive (& FUSE & NFS) are ways to do that.
