### ISSUE TITLE
Error ssh is not allowed to run bbedit on the workstation

### ISSUE THREAD

**Issue by bilke** [cngarrison/rbbedit#7]
First thanks for this great tool! Unfortunately I could not get it to work:

```bash
$ ssh server
$ rbbedit file
You must allow the application which is running `bbedit` to send events to the BBEdit application.
Please make appropriate changes in your Security & Privacy system preferences,
or contact your terminal/IDE application's developer for assistance.
bbedit: error: -1743
```

Under Privacy & Security / Automation my terminal application has permissions to run `bbedit`.

So on the workstation:

```bash
$ /usr/local/bin/bbedit localfile # works
# but this does not work:
$ ssh localhost /usr/local/bin/bbedit localfile
You must allow the application which is running `bbedit` to send events to the BBEdit application.
Please make appropriate changes in your Security & Privacy system preferences,
or contact your terminal/IDE application's developer for assistance.
bbedit: error: -1743
```

I am on macOS Sonoma 14.3. Any idea? Thanks a lot!

**Comment by cngarrison** [comment]
I have seen this problem before. I don't think it was solved. 

Rather than allowing Terminal in Privacy & Security - try allowing `sshd` since that is the source of running `bbedit` command.

You may want to contact BBSW support about it - but I'm pretty sure I asked previously, and they said it was an Apple/OS problem. 

The ssh connection (which is what runs `bbedit`) is not in the loginwindow environment, so doesn't have the same permissions. 

I don't know why it's a problem on just some systems. My hunch is that older/upgraded systems inherited a more permissive settings for handling incoming ssh connections, and new systems have locked it down.

If you are able to find a fix, please report back here.

**Comment by cngarrison** [comment]
Actually, sshd will first run a shell of some sort, that shell could be what needs to be allowed Privacy & Security.

**Comment by bilke** [comment]
Thanks for your reply!

I also tried adding `sshd` to full disk access and "Accessibility" and also enabled "Remote Application Scripting" in Sharing but it still does not work. I send an email to BBSW support. I will let you know if they have some solution.

**Comment by cngarrison** [comment]
@bilke I've released a new version of `rbbedit` to address this issue.
